const request = require('request');

async function getStuff(){
  try{

  }catch(err){
    console.log('error:', err)
  }
}
